from .image_composite_grid import NODE_CLASS_MAPPINGS as ICG_MAPPINGS
from .image_composite_grid import NODE_DISPLAY_NAME_MAPPINGS as ICG_DISPLAY
from .image_composite_grid_labels import NODE_CLASS_MAPPINGS as ICGL_MAPPINGS
from .image_composite_grid_labels import NODE_DISPLAY_NAME_MAPPINGS as ICGL_DISPLAY
from .compose_video import NODE_CLASS_MAPPINGS as CV_MAPPINGS
from .compose_video import NODE_DISPLAY_NAME_MAPPINGS as CV_DISPLAY

NODE_CLASS_MAPPINGS = {**ICG_MAPPINGS, **ICGL_MAPPINGS, **CV_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**ICG_DISPLAY, **ICGL_DISPLAY, **CV_DISPLAY}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
